<a href="https://colab.research.google.com/github/sskkyy786/AI-phabet/blob/main/pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**DEEP LEARNING WITH PyTorch**

In [ ]:
!pip list

Package                            Version
---------------------------------- -------------------
absl-py                            1.4.0
accelerate                         0.34.2
aiohappyeyeballs                   2.4.3
aiohttp                            3.10.10
aiosignal                          1.3.1
alabaster                          0.7.16
albucore                           0.0.16
albumentations                     1.4.15
altair                             4.2.2
annotated-types                    0.7.0
anyio                              3.7.1
argon2-cffi                        23.1.0
argon2-cffi-bindings               21.2.0
array_record                       0.5.1
arviz                              0.19.0
astropy                            6.1.4
astropy-iers-data                  0.2024.10.7.0.32.46
astunparse                         1.6.3
async-timeout                      4.0.3
atpublic                           4.1.0
attrs                              24.2.0
audioread        

In [ ]:
2+2

4

In [2]:
import torch
import numpy as np

Tensor - multi dimensional matrix , float32


In [ ]:
#List
my_list = [[1,2,3,4],[5,6,8]]
my_list

[[1, 2, 3, 4], [5, 6, 8]]

In [ ]:
#Numpy Arrays -> float64
arr = np.random.rand(3,4)
arr


array([[0.01466695, 0.68358421, 0.82531988, 0.84163634],
       [0.37996576, 0.96854391, 0.70209854, 0.82389281],
       [0.89698837, 0.96993907, 0.90840177, 0.7534057 ]])

In [ ]:
arr.dtype

dtype('float64')

In [ ]:
#tensors -> float32
t = torch.randn(2,3,4)
t

tensor([[[ 0.6185,  1.8278, -0.5809,  0.8729],
         [-0.2937,  0.2131, -0.4725,  0.5976],
         [ 0.7349, -1.0461,  0.7731, -0.6111]],

        [[ 1.3687,  0.7284, -0.6272,  1.2374],
         [-0.3831,  0.8832, -0.6199,  1.0756],
         [ 1.4483,  1.4081, -0.3819, -1.0363]]])

In [ ]:
t.dtype

torch.float32

In [ ]:
t0 = torch.zeros(1,2)
t0

tensor([[0., 0.]])

In [ ]:
#create tensor out of numpy array
t1 = torch.tensor(arr)
t1
#note that dtype of tensor here is float64 because of numpy arr

tensor([[0.0147, 0.6836, 0.8253, 0.8416],
        [0.3800, 0.9685, 0.7021, 0.8239],
        [0.8970, 0.9699, 0.9084, 0.7534]], dtype=torch.float64)

In [3]:
t2 = torch.arange(20)
t2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [6]:
#reshape and view
t2 = t2.reshape(4,5)
t2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])

In [8]:
# reshape if we dont know the number of items using -1
t3 = torch.arange(25)
t3

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24])

In [10]:
t3 = t3.reshape(5,-1)
t3

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

In [13]:
t4 = torch.arange(10)
t4
t4 = t4.reshape(-1,5)
t4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [14]:
t5 = torch.arange(10)
t5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
t6 = t5.view(5,2)
t6

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [16]:
t5[2] = 100
t5

tensor([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9])

In [17]:
t6

tensor([[  0,   1],
        [100,   3],
        [  4,   5],
        [  6,   7],
        [  8,   9]])

In [18]:
# Slices
t7 = torch.arange(10)
t7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
t7[7]

tensor(7)

In [20]:
t8 = t7.reshape(5,2)
t8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [21]:
t8[:,1]


tensor([1, 3, 5, 7, 9])

In [22]:
t8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [23]:
t8[1,:]

tensor([2, 3])

In [24]:
t8[1:, :]

tensor([[2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [25]:
t8[1:3, 1]

tensor([3, 5])

In [26]:
t8[1:3, 0]

tensor([2, 4])

In [35]:
#addition of tensors
t_a = torch.tensor([1,2,3,4])
t_b = torch.tensor([1,2,3,1])
t_c = torch.tensor([1,2,9,1])
t_a + t_b + t_c

tensor([ 3,  6, 15,  6])

In [36]:
#addition longhand
torch.add(t_a,t_b)    #this cant take 3 arguments

tensor([2, 4, 6, 5])

In [39]:
#subtraction
torch.sub(t_b,t_a)

tensor([ 0,  0,  0, -3])

In [40]:
#multiply
torch.mul(t_a, t_c)

tensor([ 1,  4, 27,  4])

In [41]:
#division
t_a/t_b

tensor([1., 1., 1., 4.])

In [42]:
torch.div(t_b,t_a)

tensor([1.0000, 1.0000, 1.0000, 0.2500])

In [43]:
#remainder
t_b % t_a

tensor([0, 0, 0, 1])

In [44]:
torch.remainder(t_b,t_a)

tensor([0, 0, 0, 1])

In [45]:
#exponent
torch.pow(t_a, t_b)

tensor([ 1,  4, 27,  4])

In [46]:
t_a.add(t_b)

tensor([2, 4, 6, 5])

In [47]:
#reassignment
t_a + t_b

tensor([2, 4, 6, 5])

In [48]:
t_a

tensor([1, 2, 3, 4])

In [50]:
t_a = t_a + t_b
t_a

tensor([3, 6, 9, 6])

In [51]:
t_b

tensor([1, 2, 3, 1])

In [52]:
t_a

tensor([3, 6, 9, 6])